Repository AY2425S2-CS2103T-T11-4/tp, pull requests merged in 2025-04, with the labels that each got.

#153 Update ug
  docs/UserGuide.md
Labels: type.Chore, priority.Medium, severity.Low

#156 Fixes networth not displaying error
  docs/UserGuide.md
  docs/images/HideResult.png
  docs/images/RevealResult.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/finclient/logic/parser/ParserUtil.java
  src/main/java/seedu/finclient/model/person/Networth.java
  src/test/java/seedu/finclient/logic/parser/ParserUtilTest.java
  src/test/java/seedu/finclient/model/person/NetworthTest.java
Labels: alpha-bug

#157 Fix the bug of sort order
  docs/UserGuide.md
  src/main/java/seedu/finclient/logic/commands/SortCommand.java
  src/main/java/seedu/finclient/model/order/Order.java
  src/main/java/seedu/finclient/model/person/Person.java
  src/main/java/seedu/finclient/model/person/Remark.java
  src/test/java/seedu/finclient/logic/commands/CommandTestUtil.java
  src/test/java/seedu/finclient/model/order/OrderTest.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
  src/test/java/seedu/finclient/model/person/RemarkTest.java
  src/test/java/seedu/finclient/model/person/UniquePersonListTest.java
  src/test/java/seedu/finclient/testutil/TypicalPersons.java
Labels: alpha-bug

#158 Add more test cases to PersonTest.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
Labels: alpha-bug

#160 Fix remark related alpha bug
  docs/UserGuide.md
  src/main/java/seedu/finclient/logic/commands/AddCommand.java
  src/main/java/seedu/finclient/logic/commands/EditCommand.java
  src/main/java/seedu/finclient/logic/commands/RemarkCommand.java
  src/main/java/seedu/finclient/logic/commands/RemarkUtil/CommandType.java
  src/main/java/seedu/finclient/logic/parser/AddCommandParser.java
  src/main/java/seedu/finclient/logic/parser/EditCommandParser.java
  src/main/java/seedu/finclient/logic/parser/FinClientParser.java
  src/main/java/seedu/finclient/logic/parser/ParserUtil.java
  src/main/java/seedu/finclient/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/finclient/model/person/Person.java
  src/main/java/seedu/finclient/model/person/Remark.java
  src/main/java/seedu/finclient/model/util/SampleDataUtil.java
  src/main/java/seedu/finclient/ui/PersonCard.java
  src/main/java/seedu/finclient/ui/UpcomingEventsPanel.java
  src/test/java/seedu/finclient/logic/commands/CommandTestUtil.java
  src/test/java/seedu/finclient/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/finclient/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/finclient/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/finclient/logic/parser/FinClientParserTest.java
  src/test/java/seedu/finclient/logic/parser/ParserUtilTest.java
  src/test/java/seedu/finclient/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/finclient/logic/parser/RemarkParserTest.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
  src/test/java/seedu/finclient/model/person/RemarkTest.java
  src/test/java/seedu/finclient/model/person/UniquePersonListTest.java
  src/test/java/seedu/finclient/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/finclient/testutil/PersonBuilder.java
  src/test/java/seedu/finclient/testutil/TypicalPersons.java
  src/test/java/seedu/finclient/ui/UpcomingEventsPanelTest.java
Labels: priority.High, alpha-bug

#164 fix: update order's quantity field to 64-bit long integer
  src/main/java/seedu/finclient/logic/parser/ParserUtil.java
  src/main/java/seedu/finclient/model/order/CallAuctionCalculator.java
  src/main/java/seedu/finclient/model/order/Order.java
  src/test/java/seedu/finclient/model/order/OrderTest.java
Labels: alpha-bug

#179 Update user guide
  docs/UserGuide.md
  docs/images/HideBefore.png
  docs/images/HideResult.png
Labels: type.Enhancement

#181 Add faq
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/index.md
  docs/stylesheets/main.css
  src/main/java/seedu/finclient/logic/commands/AddCommand.java
Labels: type.Chore, priority.Medium, alpha-bug

#186 Modify website landing page
  docs/index.md
Labels: type.Enhancement

#187 Modify README.md and default.md to add FAQ section
  README.md
  docs/_markbind/layouts/default.md
Labels: type.Enhancement

#278 For participation
  docs/DeveloperGuide.md
Labels: severity.High
