Repository AY2425S2-CS2103T-T11-4/tp, pull requests merged in 2025-03, with the labels that each got.

#5 Add Amos photo
  docs/images/tanjiehaoamos.png
Labels: priority.High, severity.VeryLow

#16 Update about us
  docs/AboutUs.md
  docs/team/wei-song1.md
Labels: type.Chore, priority.High, severity.VeryLow

#17 Update AboutUs page
  docs/AboutUs.md
  docs/team/tanjiehaoamos.md
Labels: priority.High, severity.VeryLow

#23 Add fengrui photo
  docs/images/rickyhfr.png
Labels: type.Chore, priority.Medium

#25 Update AboutUs Page - Fengrui
  docs/AboutUs.md
  docs/team/rickyhfr.md
Labels: type.Chore, priority.Medium

#27 Update ReadME.md
  README.md
  docs/_config.yml
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.Medium

#32 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High, severity.Medium

#49 Add sort feature
  src/main/java/seedu/finclient/logic/commands/SortCommand.java
  src/test/java/seedu/finclient/logic/commands/SortCommandTest.java
Labels: type.Story, type.Enhancement, priority.Medium

#53 fix: support hide/reveal by index
  src/main/java/seedu/finclient/logic/commands/HideCommand.java
  src/main/java/seedu/finclient/logic/commands/RevealCommand.java
  src/main/java/seedu/finclient/logic/parser/HideCommandParser.java
  src/main/java/seedu/finclient/logic/parser/RevealCommandParser.java
  src/main/java/seedu/finclient/model/FinClient.java
  src/main/java/seedu/finclient/model/Model.java
  src/main/java/seedu/finclient/model/ModelManager.java
  src/main/java/seedu/finclient/model/person/Person.java
  src/main/java/seedu/finclient/model/person/UniquePersonList.java
  src/test/java/seedu/finclient/logic/commands/AddCommandTest.java
  src/test/java/seedu/finclient/logic/commands/HideCommandTest.java
  src/test/java/seedu/finclient/logic/commands/RevealCommandTest.java
  src/test/java/seedu/finclient/logic/parser/HideCommandParserTest.java
  src/test/java/seedu/finclient/logic/parser/RevealCommandParserTest.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
  src/test/java/seedu/finclient/model/person/UniquePersonListTest.java
Labels: priority.High, severity.High

#55 Branch update help window
  build.gradle
  docs/UserGuide.md
  docs/images/helpMsg.PNG
  docs/img.png
  src/main/java/seedu/finclient/commons/core/LogsCenter.java
  src/main/java/seedu/finclient/ui/HelpWindow.java
  src/main/java/seedu/finclient/ui/MainWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, severity.Medium

#64 Add more tests for phone numbers
  src/test/java/seedu/finclient/model/person/PersonTest.java
  src/test/java/seedu/finclient/testutil/TypicalPersons.java
Labels: priority.Low, severity.Low

#65 Update developer guide
  docs/DeveloperGuide.md
  docs/images/BetterModelClassDiagram.png
Labels: priority.Low, severity.Low

#66 Add sort feature
  src/main/java/seedu/finclient/logic/commands/SortCommand.java
  src/main/java/seedu/finclient/logic/parser/CliSyntax.java
  src/main/java/seedu/finclient/logic/parser/FinClientParser.java
  src/main/java/seedu/finclient/logic/parser/ParserUtil.java
  src/main/java/seedu/finclient/logic/parser/SortCommandParser.java
  src/main/java/seedu/finclient/model/FinClient.java
  src/main/java/seedu/finclient/model/Model.java
  src/main/java/seedu/finclient/model/ModelManager.java
  src/main/java/seedu/finclient/model/person/Name.java
  src/main/java/seedu/finclient/model/person/Person.java
  src/main/java/seedu/finclient/model/person/UniquePersonList.java
  src/main/java/seedu/finclient/ui/HelpWindow.java
  src/test/java/seedu/finclient/logic/commands/AddCommandTest.java
  src/test/java/seedu/finclient/logic/commands/CommandTestUtil.java
  src/test/java/seedu/finclient/logic/commands/HideCommandTest.java
  src/test/java/seedu/finclient/logic/commands/RevealCommandTest.java
  src/test/java/seedu/finclient/logic/commands/SortCommandTest.java
  src/test/java/seedu/finclient/logic/parser/FinClientParserTest.java
  src/test/java/seedu/finclient/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
Labels: type.Enhancement, priority.High, severity.Medium

#70 Update User Guide and Help message
  docs/UserGuide.md
  docs/images/MVP feature.png
  docs/images/helpMsg.png
  src/main/java/seedu/finclient/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, severity.Medium

#74 Update HelpWindow UI color
  build.gradle
  src/main/java/seedu/finclient/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
Labels: priority.High, severity.Medium

#73 Update HelpWindow file
  build.gradle
  src/main/java/seedu/finclient/ui/HelpWindow.java
Labels: priority.High, severity.VeryLow

#75 Update HelpWindow testcase with code resued from AB4
  build.gradle
  src/main/java/seedu/finclient/ui/HelpWindow.java
  src/test/java/seedu/finclient/ui/HelpWindowTest.java
  src/test/java/seedu/finclient/ui/StageExtension.java
  src/test/java/seedu/finclient/ui/UiPartExtension.java
Labels: priority.Medium, severity.Medium

#84 fix: update hide function to work with remarks
  src/main/java/seedu/finclient/model/person/Person.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
Labels: priority.High, severity.High

#86 Make remark optional
  src/main/java/seedu/finclient/logic/parser/AddCommandParser.java
  src/main/java/seedu/finclient/storage/JsonAdaptedPerson.java
  src/main/java/seedu/finclient/ui/PersonCard.java
Labels: priority.High, severity.High

#87 Update GUI and add shortcuts
  src/main/java/seedu/finclient/logic/commands/ExitCommand.java
  src/main/java/seedu/finclient/ui/HelpWindow.java
  src/main/java/seedu/finclient/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High, severity.Low

#89 Branch call auction
  build.gradle
  src/main/java/seedu/finclient/logic/Logic.java
  src/main/java/seedu/finclient/logic/LogicManager.java
  src/main/java/seedu/finclient/logic/commands/EditCommand.java
  src/main/java/seedu/finclient/logic/commands/OrderCommand.java
  src/main/java/seedu/finclient/logic/commands/RemarkCommand.java
  src/main/java/seedu/finclient/logic/parser/AddCommandParser.java
  src/main/java/seedu/finclient/logic/parser/CliSyntax.java
  src/main/java/seedu/finclient/logic/parser/FinClientParser.java
  src/main/java/seedu/finclient/logic/parser/OrderCommandParser.java
  src/main/java/seedu/finclient/logic/parser/ParserUtil.java
  src/main/java/seedu/finclient/logic/parser/SortCommandParser.java
  src/main/java/seedu/finclient/model/FinClient.java
  src/main/java/seedu/finclient/model/Model.java
  src/main/java/seedu/finclient/model/ModelManager.java
  src/main/java/seedu/finclient/model/order/CallAuctionCalculator.java
  src/main/java/seedu/finclient/model/order/Order.java
  src/main/java/seedu/finclient/model/person/Person.java
  src/main/java/seedu/finclient/model/person/UniquePersonList.java
  src/main/java/seedu/finclient/model/util/SampleDataUtil.java
  src/main/java/seedu/finclient/storage/JsonAdaptedPerson.java
  src/main/java/seedu/finclient/ui/MainWindow.java
  src/main/java/seedu/finclient/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonFinClientStorageTest/invalidAndValidPersonFinClient.json
  src/test/data/JsonFinClientStorageTest/invalidPersonFinClient.json
  src/test/data/JsonSerializableFinClientTest/duplicatePersonFinClient.json
  src/test/data/JsonSerializableFinClientTest/typicalPersonsFinClient.json
  src/test/java/seedu/finclient/logic/LogicManagerTest.java
  src/test/java/seedu/finclient/logic/commands/AddCommandTest.java
  src/test/java/seedu/finclient/logic/commands/CommandTestUtil.java
  src/test/java/seedu/finclient/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/finclient/logic/commands/HideCommandTest.java
  src/test/java/seedu/finclient/logic/commands/OrderCommandTest.java
  src/test/java/seedu/finclient/logic/commands/RevealCommandTest.java
  src/test/java/seedu/finclient/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/finclient/logic/parser/OrderCommandParserTest.java
  src/test/java/seedu/finclient/logic/parser/ParserUtilTest.java
  src/test/java/seedu/finclient/model/order/CallAuctionCalculatorTest.java
  src/test/java/seedu/finclient/model/order/OrderTest.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
  src/test/java/seedu/finclient/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/finclient/testutil/PersonBuilder.java
  src/test/java/seedu/finclient/testutil/TypicalPersons.java
Labels: priority.High

#96 Add More fields
  docs/diagrams/BetterModelClassDiagram.puml
  src/main/java/seedu/finclient/logic/commands/EditCommand.java
  src/main/java/seedu/finclient/logic/commands/OrderCommand.java
  src/main/java/seedu/finclient/logic/commands/RemarkCommand.java
  src/main/java/seedu/finclient/logic/parser/AddCommandParser.java
  src/main/java/seedu/finclient/logic/parser/CliSyntax.java
  src/main/java/seedu/finclient/logic/parser/EditCommandParser.java
  src/main/java/seedu/finclient/logic/parser/ParserUtil.java
  src/main/java/seedu/finclient/model/person/Company.java
  src/main/java/seedu/finclient/model/person/Job.java
  src/main/java/seedu/finclient/model/person/Networth.java
  src/main/java/seedu/finclient/model/person/Person.java
  src/main/java/seedu/finclient/model/person/Remark.java
  src/main/java/seedu/finclient/model/person/StockPlatform.java
  src/main/java/seedu/finclient/model/util/SampleDataUtil.java
  src/main/java/seedu/finclient/storage/JsonAdaptedPerson.java
  src/main/java/seedu/finclient/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableFinClientTest/duplicatePersonFinClient.json
  src/test/data/JsonSerializableFinClientTest/typicalPersonsFinClient.json
  src/test/java/seedu/finclient/logic/commands/CommandTestUtil.java
  src/test/java/seedu/finclient/logic/commands/EditCommandTest.java
  src/test/java/seedu/finclient/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/finclient/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/finclient/logic/parser/ParserUtilTest.java
  src/test/java/seedu/finclient/model/person/CompanyTest.java
  src/test/java/seedu/finclient/model/person/JobTest.java
  src/test/java/seedu/finclient/model/person/NetworthTest.java
  src/test/java/seedu/finclient/model/person/PersonTest.java
  src/test/java/seedu/finclient/model/person/StockPlatformTest.java
  src/test/java/seedu/finclient/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/finclient/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/finclient/testutil/PersonBuilder.java
  src/test/java/seedu/finclient/testutil/PersonUtil.java
  src/test/java/seedu/finclient/testutil/TypicalPersons.java
  src/test/java/seedu/finclient/ui/PersonCardTest.java
Labels: type.Enhancement, priority.High, severity.High

#107 Update GUI Messages
  docs/UserGuide.md
  docs/images/helpMsg.png
  src/main/java/seedu/finclient/ui/HelpWindow.java
Labels: priority.High, severity.Medium

#111 Delete deploy.yml
  .github/workflows/deploy.yml
  docs/UserGuide.md
Labels: type.Bug

#116 Better UserGuide.md
  docs/UserGuide.md
Labels: type.Chore, priority.Medium

#115 Add in Right Navigation
  docs/AboutUs.md
  docs/Configuration.md
  docs/DeveloperGuide.md
  docs/Logging.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/index.md
  stylesheets/main.css
Labels: type.Chore

#119 Update GUI text
  docs/UserGuide.md
  docs/images/helpMsg.png
  src/main/java/seedu/finclient/ui/HelpWindow.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/finclient/ui/HelpWindowTest.java
Labels: priority.High, severity.Medium

#122 Fix User Guide and Help Message
  docs/UserGuide.md
  src/main/java/seedu/finclient/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.Low, alpha-bug

#151 Fix GUI resizing and overflow scaling issues
  src/main/java/seedu/finclient/ui/MainWindow.java
  src/main/java/seedu/finclient/ui/PersonCard.java
  src/main/java/seedu/finclient/ui/UpcomingEventsPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/UpcomingEventsPanel.fxml
Labels: priority.High, severity.High, alpha-bug
